ALTER TABLE "Institution"
  ADD COLUMN IF NOT EXISTS "institutionCategory" TEXT NOT NULL DEFAULT 'OTHER_ACCREDITED',
  ADD COLUMN IF NOT EXISTS "academicTemplateCode" TEXT NOT NULL DEFAULT 'OTHER_ACCREDITED';

ALTER TABLE "InstitutionApplication"
  ADD COLUMN IF NOT EXISTS "institutionCategory" TEXT NOT NULL DEFAULT 'OTHER_ACCREDITED',
  ADD COLUMN IF NOT EXISTS "academicTemplateCode" TEXT NOT NULL DEFAULT 'OTHER_ACCREDITED';

UPDATE "InstitutionApplication"
SET "institutionCategory" = CASE
  WHEN "type" = 'NURSERY' THEN 'NURSERY'
  WHEN "type" = 'PRIMARY' THEN 'PRIMARY'
  WHEN "type" = 'SECONDARY' THEN 'SECONDARY'
  WHEN "type" IN ('SECONDARY_JSS', 'SECONDARY_SSS') THEN 'SECONDARY'
  WHEN "type" = 'NURSERY_PRIMARY' THEN 'NURSERY_PRIMARY'
  WHEN "type" = 'PRIMARY_SECONDARY' THEN 'PRIMARY_SECONDARY'
  WHEN "type" IN ('NURSERY_PRIMARY_SECONDARY', 'COMBINED_SCHOOL') THEN 'NURSERY_PRIMARY_SECONDARY'
  WHEN "type" = 'FEDERAL_UNIVERSITY' THEN 'FEDERAL_UNIVERSITY'
  WHEN "type" = 'STATE_UNIVERSITY' THEN 'STATE_UNIVERSITY'
  WHEN "type" = 'PRIVATE_UNIVERSITY' THEN 'PRIVATE_UNIVERSITY'
  WHEN "type" = 'POLYTECHNIC' THEN 'POLYTECHNIC'
  WHEN "type" = 'COLLEGE_OF_EDUCATION' THEN 'COLLEGE_OF_EDUCATION'
  WHEN "type" = 'EXAM_BODY' THEN 'EXAM_BODY'
  ELSE 'OTHER_ACCREDITED'
END
WHERE "institutionCategory" = 'OTHER_ACCREDITED';

UPDATE "InstitutionApplication"
SET "academicTemplateCode" = CASE
  WHEN "institutionCategory" IN ('NURSERY', 'PRIMARY', 'NURSERY_PRIMARY') THEN 'BASIC_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'SECONDARY' THEN 'SECONDARY_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'PRIMARY_SECONDARY' THEN 'BASIC_SECONDARY_COMBINED_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'NURSERY_PRIMARY_SECONDARY' THEN 'FULL_BASIC_SECONDARY_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" IN ('FEDERAL_UNIVERSITY', 'STATE_UNIVERSITY', 'PRIVATE_UNIVERSITY') THEN 'UNIVERSITY_SEMESTER_COURSE_CREDIT'
  WHEN "institutionCategory" = 'POLYTECHNIC' THEN 'POLYTECHNIC_SEMESTER_ND_HND_COURSE'
  WHEN "institutionCategory" = 'COLLEGE_OF_EDUCATION' THEN 'COLLEGE_SEMESTER_NCE_COURSE'
  WHEN "institutionCategory" = 'EXAM_BODY' THEN 'EXAM_BODY_SERIES_PAPER'
  ELSE 'CUSTOM_ACADEMIC_STRUCTURE'
END;

UPDATE "Institution"
SET "institutionCategory" = CASE
  WHEN "type" = 'PRIMARY' THEN 'PRIMARY'
  WHEN "type" = 'SECONDARY' THEN 'SECONDARY'
  WHEN "type" = 'EXAM_BODY' THEN 'EXAM_BODY'
  ELSE 'OTHER_ACCREDITED'
END
WHERE "institutionCategory" = 'OTHER_ACCREDITED';

UPDATE "Institution"
SET "academicTemplateCode" = CASE
  WHEN "institutionCategory" IN ('NURSERY', 'PRIMARY', 'NURSERY_PRIMARY') THEN 'BASIC_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'SECONDARY' THEN 'SECONDARY_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'PRIMARY_SECONDARY' THEN 'BASIC_SECONDARY_COMBINED_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" = 'NURSERY_PRIMARY_SECONDARY' THEN 'FULL_BASIC_SECONDARY_TERM_CLASS_SUBJECT'
  WHEN "institutionCategory" IN ('FEDERAL_UNIVERSITY', 'STATE_UNIVERSITY', 'PRIVATE_UNIVERSITY') THEN 'UNIVERSITY_SEMESTER_COURSE_CREDIT'
  WHEN "institutionCategory" = 'POLYTECHNIC' THEN 'POLYTECHNIC_SEMESTER_ND_HND_COURSE'
  WHEN "institutionCategory" = 'COLLEGE_OF_EDUCATION' THEN 'COLLEGE_SEMESTER_NCE_COURSE'
  WHEN "institutionCategory" = 'EXAM_BODY' THEN 'EXAM_BODY_SERIES_PAPER'
  ELSE 'CUSTOM_ACADEMIC_STRUCTURE'
END;

CREATE INDEX IF NOT EXISTS "Institution_institutionCategory_idx" ON "Institution"("institutionCategory");
CREATE INDEX IF NOT EXISTS "Institution_type_status_idx" ON "Institution"("type", "status");
CREATE INDEX IF NOT EXISTS "InstitutionApplication_institutionCategory_status_idx" ON "InstitutionApplication"("institutionCategory", "status");
